apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
spec:
  selector:
    matchLabels:
      app: my-python-app
  replicas: 4
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: python-assesment-app07:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: my-python-service
spec:
  selector:
    app: my-python-app
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer